version: "3.9"
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    ports:
      - "5341:80"
    restart: unless-stopped

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

volumes:
  seq_data:
  rabbitmq_data: